"""
    Food Data Central API

    The FoodData Central API provides REST access to FoodData Central (FDC). It is intended primarily to assist application developers wishing to incorporate nutrient data into their applications or websites.   To take full advantage of the API, developers should familiarize themselves with the database by reading the database documentation available via links on [Data Type Documentation](https://fdc.nal.usda.gov/data-documentation.html). This documentation provides the detailed definitions and descriptions needed to understand the data elements referenced in the API documentation.      Additional details about the API including rate limits, access, and licensing are available on the [FDC website](https://fdc.nal.usda.gov/api-guide.html)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.fdc_api import FDCApi  # noqa: E501


class TestFDCApi(unittest.TestCase):
    """FDCApi unit test stubs"""

    def setUp(self):
        self.api = FDCApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_food(self):
        """Test case for get_food

        Fetches details for one food item by FDC ID  # noqa: E501
        """
        pass

    def test_get_foods(self):
        """Test case for get_foods

        Fetches details for multiple food items using input FDC IDs  # noqa: E501
        """
        pass

    def test_get_foods_list(self):
        """Test case for get_foods_list

        Returns a paged list of foods, in the 'abridged' format  # noqa: E501
        """
        pass

    def test_get_foods_search(self):
        """Test case for get_foods_search

        Returns a list of foods that matched search (query) keywords  # noqa: E501
        """
        pass

    def test_get_json_spec(self):
        """Test case for get_json_spec

        Returns this documentation in JSON format  # noqa: E501
        """
        pass

    def test_get_yaml_spec(self):
        """Test case for get_yaml_spec

        Returns this documentation in JSON format  # noqa: E501
        """
        pass

    def test_post_foods(self):
        """Test case for post_foods

        Fetches details for multiple food items using input FDC IDs  # noqa: E501
        """
        pass

    def test_post_foods_list(self):
        """Test case for post_foods_list

        Returns a paged list of foods, in the 'abridged' format  # noqa: E501
        """
        pass

    def test_post_foods_search(self):
        """Test case for post_foods_search

        Returns a list of foods that matched search (query) keywords  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
